"""Curated data catalogue and source connector definitions."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Dataset:
    id: str
    title: str
    theme: str
    publisher: str
    description: str
    url: str
    access: str
    cadence: str
    format: str
    scope: str
    limitations: str
    license_terms: str = "Consultar a licença e os termos de uso publicados pelo órgão para este conjunto."
    source_version: str = "Consultar a versão e o esquema documentados pela fonte."
    endpoint: str | None = None
    connector: str | None = None
    default_params: tuple[tuple[str, str], ...] = ()
    required_params: tuple[str, ...] = ()
    federal_filter: bool = False
    page_param: str = "pagina"


DATASETS = (
    Dataset(
        id="cgu_despesas_orgao",
        title="Despesas federais por órgão",
        theme="Gastos e contratações",
        publisher="Controladoria-Geral da União (CGU)",
        description="Valores anuais de despesas do Poder Executivo Federal por órgão.",
        url="https://portaldatransparencia.gov.br/api-de-dados",
        access="API REST; requer token de acesso obtido por e-mail cadastrado.",
        cadence="Atualização conforme publicação do Portal da Transparência.",
        format="JSON",
        scope="Poder Executivo Federal; filtrado por órgão superior.",
        limitations="Informe --param orgaoSuperior=CODIGO_SIAFI. Respeite o limite de requisições da CGU.",
        license_terms="Dados abertos da CGU; atribuir a fonte e conferir os termos publicados pelo Portal.",
        source_version="API REST v1 (OpenAPI do Portal da Transparência).",
        endpoint="https://api.portaldatransparencia.gov.br/api-de-dados/despesas/por-orgao",
        connector="cgu",
        required_params=("ano", "orgaoSuperior"),
    ),
    Dataset(
        id="compras_contratacoes",
        title="Contratações federais sob a Lei 14.133/2021",
        theme="Gastos e contratações",
        publisher="Ministério da Gestão e da Inovação em Serviços Públicos (MGI)",
        description="Contratações e itens registrados no Compras.gov.br, com consulta pública e arquivos abertos.",
        url="https://www.gov.br/compras/pt-br/cidadao/portal-de-dados-abertos/portal-de-dados-abertos",
        access="API REST oficial; consulta uma janela curta recente e aceita filtros extras com --param nome=valor.",
        cadence="Contínua, conforme o registro e a publicação das contratações.",
        format="JSON",
        scope="Compras.gov.br; órgãos federais e entidades que usam o sistema.",
        limitations="O padrão busca modalidade 5; resultados sem esfera federal explícita são descartados. Consulte a documentação atual para outros filtros.",
        license_terms="Dados abertos do Compras.gov.br; conferir atribuição e termos publicados pelo MGI.",
        source_version="API de Dados Abertos 2.0; confirmar a versão vigente antes de processamentos longos.",
        endpoint="https://dadosabertos.compras.gov.br/modulo-contratacoes/1_consultarContratacoes_PNCP_14133",
        connector="generic",
        default_params=(("codigoModalidade", "5"),),
        federal_filter=True,
    ),
    Dataset(
        id="pncp_contratacoes",
        title="Contratações publicadas no PNCP",
        theme="Gastos e contratações",
        publisher="Ministério da Gestão e da Inovação em Serviços Públicos (MGI)",
        description="Contratações publicadas no Portal Nacional de Contratações Públicas.",
        url="https://pncp.gov.br/api/consulta/swagger-ui/index.html",
        access="API REST pública de consulta; use --param para filtros adicionais.",
        cadence="Contínua, segundo as publicações e retificações dos órgãos.",
        format="JSON",
        scope="PNCP nacional; os resultados são filtrados para registros com esfera federal.",
        limitations="A API inclui vários níveis de governo; registros sem esfera federal identificável são descartados.",
        license_terms="Dados públicos do PNCP; citar o PNCP e consultar os termos vigentes.",
        source_version="API de consulta v1; o órgão contratante é responsável pelos registros publicados.",
        endpoint="https://pncp.gov.br/api/consulta/v1/contratacoes/publicacao",
        connector="pncp",
        federal_filter=True,
    ),
    Dataset(
        id="tesouro_divida_publica",
        title="Dívida Pública Federal",
        theme="Finanças públicas e economia",
        publisher="Secretaria do Tesouro Nacional (STN)",
        description="Estoque, emissões, resgates e fatores de variação da dívida pública.",
        url="https://www.tesourotransparente.gov.br/ckan/organization/dadd10a9-04ff-47f0-bf89-0092b51544a7",
        access="Arquivos abertos do Tesouro Transparente (conector futuro).",
        cadence="Mensal, conforme a publicação do Tesouro.",
        format="CSV/XLSX",
        scope="Governo Federal.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="siconfi_contas_publicas",
        title="Contas públicas e relatórios fiscais",
        theme="Finanças públicas e economia",
        publisher="Secretaria do Tesouro Nacional (STN)",
        description="Dados fiscais e contábeis disponibilizados pelo SICONFI.",
        url="https://apidatalake.tesouro.gov.br/docs/siconfi/",
        access="API REST Data Lake do Tesouro (conector futuro).",
        cadence="Periódica, conforme entrega e homologação de declarações.",
        format="JSON",
        scope="Entes federativos; será necessário filtrar para o Governo Federal.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="bcb_series_economicas",
        title="Indicadores monetários e financeiros",
        theme="Finanças públicas e economia",
        publisher="Banco Central do Brasil (BCB)",
        description="Séries temporais de juros, crédito, câmbio, inflação e outros indicadores.",
        url="https://dadosabertos.bcb.gov.br/",
        access="Catálogo e APIs de dados abertos do Banco Central (conector futuro).",
        cadence="Varia por série; diária a mensal.",
        format="JSON/CSV",
        scope="Brasil.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="ibge_sidra_indicadores",
        title="Estatísticas econômicas e demográficas",
        theme="População e território",
        publisher="Instituto Brasileiro de Geografia e Estatística (IBGE)",
        description="Tabelas agregadas de pesquisas econômicas, censos e indicadores sociais.",
        url="https://sidra.ibge.gov.br/",
        access="API SIDRA e downloads do IBGE (conector futuro).",
        cadence="Varia conforme a pesquisa e a tabela.",
        format="JSON/CSV",
        scope="Brasil e subdivisões territoriais.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="orcamento_federal",
        title="Orçamento e execução orçamentária federal",
        theme="Finanças públicas e economia",
        publisher="Ministério do Planejamento e Orçamento (MPO)",
        description="LOA, execução orçamentária e relatórios do Governo Central.",
        url="https://www.gov.br/planejamento/pt-br/assuntos/orcamento",
        access="Relatórios e dados oficiais de orçamento (conector futuro).",
        cadence="Anual para peças orçamentárias; periódica para execução.",
        format="CSV/XLSX/PDF",
        scope="Governo Federal.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="transferencias_federais",
        title="Transferências e convênios federais",
        theme="Gastos e contratações",
        publisher="Controladoria-Geral da União (CGU)",
        description="Transferências de recursos federais, convênios e instrumentos relacionados.",
        url="https://portaldatransparencia.gov.br/transferencias",
        access="Portal da Transparência e API da CGU; pode exigir token (conector futuro).",
        cadence="Conforme os registros dos órgãos concedentes.",
        format="API/CSV",
        scope="Recursos federais, inclusive transferidos a outros entes.",
        limitations="Ainda não possui conector de download nesta versão; evitar consultas por identificador pessoal.",
    ),
    Dataset(
        id="beneficios_federais",
        title="Benefícios e programas federais (dados agregados)",
        theme="Serviços e políticas públicas",
        publisher="Controladoria-Geral da União (CGU)",
        description="Despesas e totais de programas de benefícios federais em agregações públicas.",
        url="https://portaldatransparencia.gov.br/api-de-dados",
        access="Portal da Transparência e API da CGU; pode exigir token (conector futuro).",
        cadence="Conforme publicação de cada programa.",
        format="API/CSV",
        scope="Programas federais; análises agregadas por período e território.",
        limitations="Não importar nomes, CPF, NIS ou registros individualizados de beneficiários.",
    ),
    Dataset(
        id="emprego_rais_caged",
        title="Emprego formal, RAIS e Novo CAGED",
        theme="Serviços e políticas públicas",
        publisher="Ministério do Trabalho e Emprego (MTE)",
        description="Microdados não identificados e estatísticas de admissões, desligamentos e vínculos formais.",
        url="https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/estatisticas-trabalho/microdados-rais-e-caged",
        access="Downloads oficiais do PDET/MTE (conector futuro).",
        cadence="Mensal para Novo CAGED; anual para RAIS.",
        format="TXT/CSV/ZIP",
        scope="Brasil e recortes territoriais.",
        limitations="Usar apenas versões públicas não identificadas; arquivos são grandes e requerem dicionário de dados.",
    ),
    Dataset(
        id="datasus_saude",
        title="Indicadores e produção de saúde",
        theme="Serviços e políticas públicas",
        publisher="Ministério da Saúde / DATASUS",
        description="Bases e indicadores de estabelecimentos, atendimentos e produção de saúde.",
        url="https://datasus.saude.gov.br/servicos/",
        access="APIs e arquivos oficiais do DATASUS (conector futuro).",
        cadence="Varia por sistema e conjunto de dados.",
        format="CSV/DBF/API",
        scope="Brasil e unidades territoriais.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="inep_educacao",
        title="Censos e indicadores educacionais",
        theme="Serviços e políticas públicas",
        publisher="Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP)",
        description="Censos escolares e da educação superior, avaliações e indicadores educacionais.",
        url="https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos",
        access="Arquivos e painéis oficiais do INEP (conector futuro).",
        cadence="Varia por pesquisa; em geral anual.",
        format="CSV/XLSX/ZIP",
        scope="Brasil e subdivisões territoriais.",
        limitations="Microdados podem ter acesso ou granularidade limitados para proteger privacidade.",
    ),
    Dataset(
        id="tse_dados_eleitorais",
        title="Dados eleitorais",
        theme="Estado e democracia",
        publisher="Tribunal Superior Eleitoral (TSE)",
        description="Resultados eleitorais, candidaturas, partidos e prestação de contas eleitorais.",
        url="https://dadosabertos.tse.jus.br/",
        access="Portal oficial de dados abertos do TSE (conector futuro).",
        cadence="Por ciclo eleitoral e atualizações do TSE.",
        format="CSV/ZIP",
        scope="Brasil e unidades territoriais.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="seguranca_publica",
        title="Estatísticas nacionais de segurança pública",
        theme="Serviços e políticas públicas",
        publisher="Ministério da Justiça e Segurança Pública (MJSP)",
        description="Indicadores nacionais publicados pelo sistema de informações de segurança pública.",
        url="https://www.gov.br/mj/pt-br/assuntos/sua-seguranca/seguranca-publica/estatistica",
        access="Publicações e bases oficiais do MJSP/SINESP (conector futuro).",
        cadence="Varia por indicador e boletim.",
        format="XLSX/CSV/PDF",
        scope="Brasil e unidades federativas.",
        limitations="Ainda não possui conector de download nesta versão; considerar que séries e definições podem mudar.",
    ),
    Dataset(
        id="justica_indicadores",
        title="Indicadores do sistema de justiça",
        theme="Estado e democracia",
        publisher="Conselho Nacional de Justiça (CNJ)",
        description="Estatísticas agregadas sobre processos, tribunais, força de trabalho e produtividade judicial.",
        url="https://www.cnj.jus.br/pesquisas-judiciarias/justica-em-numeros/",
        access="Painéis e relatórios oficiais do CNJ (conector futuro).",
        cadence="Anual, com séries históricas.",
        format="XLSX/CSV/PDF",
        scope="Judiciário brasileiro, com recortes por tribunal.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="aneel_energia",
        title="Regulação, geração e distribuição de energia elétrica",
        theme="Infraestrutura e recursos",
        publisher="Agência Nacional de Energia Elétrica (ANEEL)",
        description="Tarifas, geração, distribuição e fiscalização do setor elétrico.",
        url="https://dadosabertos.aneel.gov.br/",
        access="Portal de dados abertos da ANEEL e API CKAN (conector futuro).",
        cadence="Varia por conjunto; de diária a periódica.",
        format="CSV/JSON/Parquet/ZIP",
        scope="Brasil e unidades territoriais.",
        limitations="Ainda não possui conector de download nesta versão; cada conjunto tem sua própria frequência e licença.",
    ),
    Dataset(
        id="anp_petroleo_combustiveis",
        title="Petróleo, gás natural e combustíveis",
        theme="Infraestrutura e recursos",
        publisher="Agência Nacional do Petróleo, Gás Natural e Biocombustíveis (ANP)",
        description="Dados abertos de produção, preços, revenda e regulação de combustíveis.",
        url="https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/dados-abertos",
        access="Arquivos e conjuntos publicados pela ANP (conector futuro).",
        cadence="Varia por conjunto e levantamento.",
        format="CSV/XLSX",
        scope="Brasil e recortes territoriais.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="inpe_monitoramento_ambiental",
        title="Queimadas, cobertura e monitoramento ambiental",
        theme="Infraestrutura e recursos",
        publisher="Instituto Nacional de Pesquisas Espaciais (INPE)",
        description="Monitoramento de queimadas, desmatamento e outros dados geoespaciais ambientais.",
        url="https://www.gov.br/inpe/pt-br/acesso-a-informacao/dados-abertos/monitoramento-ambiental",
        access="Portais, arquivos e serviços oficiais do INPE (conector futuro).",
        cadence="Varia por sistema; alguns produtos são diários.",
        format="CSV/JSON/GeoJSON/OGC",
        scope="Brasil e biomas.",
        limitations="Ainda não possui conector de download nesta versão; interpretar os dados conforme metadados e metodologia de cada produto.",
    ),
    Dataset(
        id="antt_transportes",
        title="Rodovias, ferrovias e transporte terrestre",
        theme="Infraestrutura e recursos",
        publisher="Agência Nacional de Transportes Terrestres (ANTT)",
        description="Dados sobre concessões, cargas, passageiros, fiscalização e infraestrutura de transporte terrestre.",
        url="https://dados.antt.gov.br/",
        access="Portal oficial de dados abertos e painéis da ANTT (conector futuro).",
        cadence="Varia por base e painel.",
        format="CSV/JSON/XLSX",
        scope="Brasil e corredores de transporte.",
        limitations="Ainda não possui conector de download nesta versão.",
    ),
    Dataset(
        id="anatel_telecomunicacoes",
        title="Acesso, qualidade e infraestrutura de telecomunicações",
        theme="Infraestrutura e recursos",
        publisher="Agência Nacional de Telecomunicações (ANATEL)",
        description="Indicadores de serviços, infraestrutura e regulação de telecomunicações.",
        url="https://www.gov.br/anatel/pt-br/dados/dados-abertos",
        access="Bases da ANATEL e Portal Brasileiro de Dados Abertos (conector futuro).",
        cadence="Varia por base; dados setoriais e consolidados.",
        format="CSV/JSON",
        scope="Brasil e municípios, conforme a base.",
        limitations="Ainda não possui conector de download nesta versão; algumas bases são publicadas apenas agregadas.",
    ),
    Dataset(
        id="conab_agricultura",
        title="Safras, estoques e preços agropecuários",
        theme="Infraestrutura e recursos",
        publisher="Companhia Nacional de Abastecimento (CONAB)",
        description="Indicadores de safra, abastecimento, estoques públicos, custos e preços agrícolas.",
        url="https://portaldeinformacoes.conab.gov.br/",
        access="Painéis, consultas e publicações oficiais da CONAB (conector futuro).",
        cadence="Varia por produto; semanal a anual.",
        format="XLSX/CSV/PDF",
        scope="Brasil e regiões produtoras.",
        limitations="Ainda não possui conector de download nesta versão; alguns produtos têm restrições de uso próprias.",
    ),
    Dataset(
        id="legislacao_federal",
        title="Legislação federal e atos normativos",
        theme="Estado e democracia",
        publisher="Presidência da República / Casa Civil",
        description="Base pesquisável de normas federais de hierarquia superior, mantida e atualizada pela Presidência.",
        url="https://www4.planalto.gov.br/legislacao/portal-legis/busca-avancada",
        access="Base oficial de legislação; formatos e interface de consulta variam por norma (conector futuro).",
        cadence="Atualizada conforme publicação e consolidação das normas.",
        format="HTML/PDF",
        scope="Legislação federal.",
        limitations="Ainda não possui conector de download nesta versão; textos integrais estão disponíveis apenas para parte dos registros.",
    ),
    Dataset(
        id="dados_ambientais",
        title="Clima, energia, agricultura e meio ambiente",
        theme="Infraestrutura e recursos",
        publisher="Órgãos federais responsáveis por cada base (INPE, IBAMA, ANEEL, ANP e outros)",
        description="Catálogo temático para indicadores ambientais e de recursos naturais publicados por órgãos federais.",
        url="https://dados.gov.br/",
        access="Identificar a base e a fonte oficial no catálogo antes de implementar cada conector.",
        cadence="Varia por fonte e indicador.",
        format="API/CSV/GeoJSON",
        scope="Brasil.",
        limitations="Cada conjunto precisa ser verificado individualmente quanto a cobertura, licença e atualização.",
    ),
)


def get_dataset(dataset_id: str) -> Dataset:
    for dataset in DATASETS:
        if dataset.id == dataset_id:
            return dataset
    raise KeyError(dataset_id)
