export const chartGuides = {
  debt: {
    title: "Estoque e composição da DPF",
    summary: "Acompanhe o estoque mensal da dívida federal e sua divisão entre componentes internos e externos.",
    represents: "Mostra o saldo mensal da Dívida Pública Federal em poder do público, separado em dívida interna (DPMFi) e externa (DPFe), em reais correntes.",
    interpretation: "Compare a trajetória e a composição ao longo do tempo. Uma alta do estoque não é, por si só, igual a gasto novo: juros apropriados, emissões líquidas, câmbio e outros ajustes também alteram o saldo. Valores nominais não descontam inflação.",
    importance: "O estoque revela o tamanho e a estrutura das obrigações federais que o Tesouro precisa administrar e refinanciar.",
    study: "Estude títulos públicos, dívida bruta e líquida, resultado primário, necessidade de financiamento, indexadores, maturidade e risco cambial. Consulte também os fatores de variação da DPF.",
  },
  macro: {
    title: "Dívida bruta e líquida em proporção do PIB",
    summary: "DBGG e DLGG medem a dívida do governo geral em relação ao PIB e têm escopo maior que a DPF.",
    represents: "Séries mensais do Banco Central para a Dívida Bruta do Governo Geral (DBGG) e a Dívida Líquida do Governo Geral (DLGG), expressas como percentual do PIB.",
    interpretation: "A razão relaciona o estoque de dívida ao tamanho anual da economia. DBGG e DLGG têm conceitos distintos e abrangem União, estados e municípios; não são a DPF do Tesouro. Mudanças podem refletir dívida, PIB, câmbio e outros ajustes.",
    importance: "A proporção ajuda a comparar o endividamento com a capacidade econômica do país e contextualiza a escala da dívida ao longo do tempo.",
    study: "Estude conceitos de dívida bruta e líquida, setor público não financeiro, metodologia fiscal do BCB, PIB nominal, resultado primário e dinâmica da dívida.",
  },
  factors: {
    title: "Fatores de variação do estoque da DPF",
    summary: "A variação do estoque combina juros apropriados, emissões líquidas e outros fatores registrados pelo Tesouro.",
    represents: "Decompõe a mudança mensal da DPF em fatores divulgados pelo Tesouro, como juros apropriados e emissão ou resgate líquido, além do total dos fatores.",
    interpretation: "Leia os valores como contribuições para a variação do saldo no mês. Juros apropriados são registrados por competência; emissão líquida é captação menos resgates. A soma dos fatores deve ser interpretada com as regras e ajustes do relatório do Tesouro.",
    importance: "A decomposição distingue a origem das mudanças do estoque e evita atribuir toda expansão da dívida a novas despesas primárias.",
    study: "Estude contabilidade por competência, emissão e resgate de títulos, resultado primário, reconhecimento de passivos, ajustes patrimoniais e a metodologia dos fatores da DPF.",
  },
  interest: {
    title: "Juros apropriados e taxa implícita aproximada",
    summary: "Juros apropriados são registrados por competência e não equivalem aos pagamentos em caixa do mesmo ano.",
    represents: "As barras somam os juros apropriados na DPF por ano. A linha mostra uma razão analítica entre esse fluxo e o estoque médio anual, apenas para anos completos.",
    interpretation: "A apropriação é um registro por competência e não equivale ao pagamento em caixa no mesmo período. A taxa calculada pelo painel é aproximada; não substitui o custo médio oficial da dívida divulgado pelo Tesouro.",
    importance: "Os juros ajudam a dimensionar o custo financeiro acumulado e a compreender como indexadores e taxas afetam a trajetória do estoque.",
    study: "Estude juros nominais e reais, apropriação versus caixa, custo médio oficial da DPF, indexadores dos títulos, prazo médio e risco de refinanciamento.",
  },
  spending: {
    title: "Execução paga por função orçamentária",
    summary: "A série compara pagamentos federais em saúde, educação e segurança em reais corrigidos pelo IPCA.",
    represents: "Despesas pagas pelo orçamento federal nas funções Saúde, Educação e Segurança Pública, corrigidas pelo IPCA para reais de 2025.",
    interpretation: "Valores reais permitem comparar poder de compra entre anos. Pagamento não é o mesmo que dotação autorizada ou empenho. A classificação por função inclui diferentes tipos de despesa e não cobre automaticamente os orçamentos estaduais e municipais.",
    importance: "A série mostra a escala e a evolução dos recursos federais executados em áreas centrais de política pública.",
    study: "Estude ciclo orçamentário, funções e subfunções, empenho, liquidação e pagamento, IPCA, gasto obrigatório e discricionário e repartição federativa do financiamento.",
  },
  capital: {
    title: "Investimento de capital (GND 4)",
    summary: "GND 4 mostra uma parcela do gasto pago classificada como investimento, não todo o orçamento da política.",
    represents: "Mostra a despesa paga classificada como Grupo de Natureza da Despesa 4 — Investimentos — nas três funções, em valores corrigidos para reais de 2025.",
    interpretation: "GND 4 é uma parte do total pago, não todo o gasto da política. O volume executado não informa sozinho se a obra foi concluída, se o ativo está operando ou qual resultado social foi alcançado.",
    importance: "Investimentos podem ampliar ou modernizar a capacidade de prestação de serviços, mas sua leitura exige acompanhar execução física e manutenção futura.",
    study: "Estude classificação por GND, investimento público, restos a pagar, execução física, avaliação de projetos, custo do ciclo de vida e orçamento de capital.",
  },
  bpc: {
    title: "Beneficiários do BPC por grupo",
    summary: "A cobertura anual do BPC separa beneficiários idosos e pessoas com deficiência.",
    represents: "Série anual de pessoas beneficiárias do Benefício de Prestação Continuada, separadas entre pessoas idosas e pessoas com deficiência.",
    interpretation: "As contagens refletem cobertura registrada na série administrativa anual. Mudanças podem decorrer de demografia, critérios legais, concessões, revisões cadastrais e gestão; não medem isoladamente pobreza ou impacto causal.",
    importance: "O BPC é uma transferência de renda de grande escala e a evolução da cobertura ajuda a acompanhar o alcance dessa política de proteção social.",
    study: "Estude a LOAS, critérios de elegibilidade do BPC, envelhecimento populacional, deficiência, Cadastro Único, cobertura e avaliação de políticas sociais.",
  },
  socialSpend: {
    title: "Repasses informados para Bolsa Família e BPC",
    summary: "Os valores contextualizam repasses de programas com públicos, unidades e perímetros distintos.",
    represents: "Compara valores nominais reportados em 2024 para repasses do Bolsa Família e do BPC, em bilhões de reais.",
    interpretation: "Os números vêm de fontes e perímetros administrativos distintos. Famílias alcançadas pelo Bolsa Família e beneficiários do BPC são unidades diferentes; não some coberturas nem interprete valores como benefício médio individual comparável.",
    importance: "A comparação contextualiza a escala fiscal de programas importantes de transferência de renda, preservando diferenças de público e contabilidade.",
    study: "Estude desenho de transferências condicionadas e não condicionadas, benefícios previdenciários e assistenciais, cobertura, focalização e indicadores de pobreza.",
  },
  pibNominal: {
    title: "PIB nominal e atividade por setor",
    summary: "Valores correntes combinam preços e quantidades; crescimento nominal não representa crescimento real.",
    represents: "Mostra valores correntes trimestrais, semestrais ou anuais do PIB e de setores selecionados, segundo as Contas Nacionais Trimestrais do IBGE.",
    interpretation: "Valores correntes somam preços e quantidades do período. Crescer nominalmente não significa produzir mais em termos reais. Os setores apresentados são componentes do PIB e não devem ser somados novamente ao total.",
    importance: "O PIB mede a escala da atividade econômica e fornece contexto para dívida, arrecadação e gasto público.",
    study: "Estude Sistema de Contas Nacionais, valor adicionado, preços correntes e constantes, deflator do PIB, índice de volume encadeado e ajuste sazonal.",
  },
  pibGrowth: {
    title: "Crescimento real do PIB por setor",
    summary: "As taxas reais medem variações de volume; cada comparação trimestral, anual ou semestral tem uma definição própria.",
    represents: "Apresenta taxas de variação do índice de volume do PIB e dos setores, incluindo comparações oficiais do IBGE e, quando selecionado, a taxa semestral derivada pelo projeto.",
    interpretation: "Trimestre contra trimestre com ajuste sazonal, mesmo trimestre do ano anterior, acumulado no ano e comparação semestral são medidas diferentes. A taxa derivada de semestre não é uma publicação oficial independente do IBGE.",
    importance: "As taxas reais isolam a mudança de volume da variação dos preços e ajudam a identificar ciclos e diferenças entre setores.",
    study: "Estude índices de volume, ajuste sazonal, efeitos de base, séries encadeadas, crescimento acumulado e revisões das Contas Nacionais.",
  },
  pibSpending: {
    title: "Componentes da despesa do PIB",
    summary: "Consumo, investimento e comércio exterior ajudam a descrever a composição da atividade econômica.",
    represents: "Mostra a variação real de consumo das famílias e do governo, formação de capital, exportações e importações nas Contas Nacionais do IBGE.",
    interpretation: "São componentes da ótica da despesa. Importações entram com sinal negativo na identidade contábil, mas a taxa de crescimento do componente não é sua contribuição direta para o crescimento do PIB.",
    importance: "A composição da despesa mostra quais componentes acompanham ou explicam a dinâmica da atividade, sem confundir crescimento de um componente com contribuição em pontos percentuais.",
    study: "Estude identidade do PIB pela despesa, consumo, formação bruta de capital fixo, variação de estoques, exportações líquidas e decomposição de crescimento.",
  },
  taxes: {
    title: "Arrecadação federal mensal",
    summary: "A arrecadação nominal soma os meses publicados e não desconta inflação nem projeta dias ainda não divulgados.",
    represents: "Soma nominal das receitas federais administradas pela Receita Federal e por outros órgãos, em valores mensais divulgados pela RFB.",
    interpretation: "A linha administrada pela RFB é detalhada a partir de 2021; o total federal é a série de referência. Valores correntes e variação nominal em 12 meses não descontam inflação nem isolam efeitos de atividade, legislação ou composição.",
    importance: "A arrecadação é uma fonte de financiamento do governo federal e ajuda a contextualizar o espaço fiscal, sem equivaler a receita disponível após transferências e despesas.",
    study: "Estude receita corrente, tributos e contribuições, repartição de receitas, carga tributária, elasticidade da arrecadação, inflação e resultado fiscal.",
  },
  taxBurden: {
    title: "Carga tributária bruta do Governo Geral",
    summary: "A carga tributária anual relaciona tributos da União, estados e municípios ao PIB.",
    represents: "Carga tributária anual calculada pelo Tesouro Nacional para Governo Central, estados e municípios, apresentada como percentual do PIB.",
    interpretation: "A série consolidada mede tributos em relação ao PIB e tem frequência anual. Não deve ser somada à arrecadação federal mensal, pois os escopos e períodos diferem.",
    importance: "O indicador permite acompanhar a participação da arrecadação tributária na economia e comparar a distribuição entre esferas públicas.",
    study: "Estude carga tributária bruta, incidência e base tributária, federalismo fiscal, repartição de receitas, PIB nominal e comparabilidade internacional.",
  },
  purchasingPower: {
    title: "Preços desde a implementação do real",
    summary: "O IPCA mostra a mudança média do nível de preços no país desde julho de 1994.",
    represents: "O gráfico mostra quanto custaria, em cada mês, uma cesta de consumo que custava R$ 100 em julho de 1994. A série é construída com as variações mensais do IPCA.",
    interpretation: "O preço acumulado é composto multiplicando os fatores mensais de agosto de 1994 até o último IPCA disponível. A diferença representa inflação acumulada; a perda do poder de compra de R$ 1 é calculada como 1 menos o inverso desse fator. É uma medida de preços no Brasil, não da cotação do real frente ao dólar.",
    importance: "A série mostra por que valores nominais de décadas diferentes não são diretamente comparáveis e quantifica a erosão do poder de compra da moeda ao longo do tempo.",
    study: "Estude IPCA e cesta de consumo, números-índice, inflação acumulada e composta, inflação média versus inflação pessoal, indexação e correção monetária.",
  },
};
