<script setup>
import { inject, toRefs } from "vue";
import { ArrowUpRight } from "@lucide/vue";
import TrendChart from "../components/TrendChart.vue";
const { page, data, activeData, debtLatest, interestLatest, interestAnnualLast, completeInterestYears, latestInterestYear, interestYearChange, cumulativeInterest, pretty, tri, percent, month, debtChart, macroChart, factorsChart, interestChart, chartGuides, go } = toRefs(inject("dashboard"));
</script>

<template>
<section class="content inner-content">
          <div class="page-intro"><div><div class="eyebrow"><span></span> DÍVIDA PÚBLICA FEDERAL</div><h1 tabindex="-1">Uma trajetória de <em>25 anos.</em></h1><p>Estoque, juros apropriados e composição para acompanhar o endividamento federal.</p></div><aside>ÚLTIMA COMPETÊNCIA<strong>{{ month(debtLatest?.data) }}</strong></aside></div>
          <div class="metrics">
            <article class="metric metric-blue"><div class="metric-label">ESTOQUE DPF</div><strong>R$ {{ tri(debtLatest?.dpf_bilhoes) }} <small>tri</small></strong><div class="metric-foot"><span>Em poder do público</span></div></article>
            <article class="metric metric-teal"><div class="metric-label">DPMFi · INTERNA</div><strong>R$ {{ tri(debtLatest?.dpmfi_bilhoes) }} <small>tri</small></strong><div class="metric-foot"><span>{{ percent(100 * debtLatest?.dpmfi_bilhoes / debtLatest?.dpf_bilhoes) }} do estoque</span></div></article>
            <article class="metric metric-red"><div class="metric-label">DPFe · EXTERNA</div><strong>R$ {{ tri(debtLatest?.dpfe_bilhoes) }} <small>tri</small></strong><div class="metric-foot"><span>{{ percent(100 * debtLatest?.dpfe_bilhoes / debtLatest?.dpf_bilhoes) }} do estoque</span></div></article>
            <article class="metric metric-gold"><div class="metric-label">JUROS APROPRIADOS · MÊS</div><strong>R$ {{ pretty(interestLatest?.juros_dpf_bilhoes, 1) }} <small>bi</small></strong><div class="metric-foot"><span>{{ month(interestLatest?.data) }}</span><i>Competência · Tesouro</i></div></article>
          </div>
          <div class="interest-summary">
            <article><span>ACUMULADO NO ANO ATÉ {{ month(interestLatest?.data) }}</span><strong>R$ {{ pretty(interestAnnualLast?.juros_dpf_bilhoes, 1) }} bi</strong></article>
            <article><span>JUROS EM {{ latestInterestYear?.ano }}</span><strong>R$ {{ pretty(latestInterestYear?.juros_dpf_bilhoes, 1) }} bi</strong></article>
            <article><span>VARIAÇÃO ANUAL</span><strong>{{ percent(interestYearChange) }}</strong></article>
            <article><span>ACUMULADO {{ completeInterestYears[0]?.ano }}–{{ latestInterestYear?.ano }}</span><strong>R$ {{ tri(cumulativeInterest) }} tri</strong></article>
          </div>
          <div class="stacked-panels">
            <article class="panel"><div class="panel-heading"><div><span class="kicker">R$ CORRENTES</span><h3>Estoque total e composição</h3></div><span class="unit-pill">2000–2026</span></div><TrendChart :option="debtChart" :guide="chartGuides.debt" height="430px" /><p class="panel-caption">DPMFi e DPFe compõem o total da DPF em poder do público.</p></article>
            <div class="dashboard-grid">
              <article class="panel"><div class="panel-heading"><div><span class="kicker">BANCO CENTRAL · SGS</span><h3>Dívida bruta e líquida</h3></div><span class="unit-pill">% do PIB</span></div><TrendChart :option="macroChart" :guide="chartGuides.macro" height="340px" /><p class="panel-caption">Indicadores de governo geral; perímetro diferente da DPF.</p></article>
            </div>
            <article class="panel"><div class="panel-heading"><div><span class="kicker">TESOURO NACIONAL</span><h3>Fatores de variação da DPF</h3></div><span class="unit-pill">R$ bilhões · série mensal</span></div><TrendChart :option="factorsChart" :guide="chartGuides.factors" height="405px" /><p class="panel-caption">Juros apropriados, emissão líquida e total dos fatores. O gráfico ocupa a largura da página para facilitar a leitura das séries longas.</p></article>
            <article class="panel"><div class="panel-heading"><div><span class="kicker">2007 — {{ interestAnnualLast?.ano }}</span><h3>Juros apropriados por ano</h3></div><span class="unit-pill">R$ bi · taxa aproximada</span></div><TrendChart :option="interestChart" :guide="chartGuides.interest" height="375px" /><div class="interest-legend"><span><i></i> Juros apropriados no ano</span><span><i></i> Taxa implícita aproximada</span></div><p class="panel-caption">O valor anual soma a apropriação por competência dos juros e encargos da DPF. A taxa aproximada divide esse fluxo pelo estoque médio anual e só é calculada para anos completos. 2026 está parcial até {{ month(interestLatest?.data) }}. Essa razão não substitui o custo médio oficial do Tesouro.</p></article>
            <article class="panel methods"><div class="panel-heading"><div><span class="kicker">MÉTRICAS E EXEMPLO</span><h3>DPF, DBGG e proporção sobre o PIB</h3></div></div><div class="method-row"><span>01</span><div><strong>Estoque da DPF</strong><p>Saldo da dívida federal sob responsabilidade do Tesouro, em R$ correntes na série mostrada. Exemplo de composição na última competência: {{ percent(100 * debtLatest?.dpmfi_bilhoes / debtLatest?.dpf_bilhoes) }} é dívida interna (DPMFi) e {{ percent(100 * debtLatest?.dpfe_bilhoes / debtLatest?.dpf_bilhoes) }} é externa (DPFe).</p></div></div><div class="method-row"><span>02</span><div><strong>Razão dívida / PIB</strong><p>O BCB publica DBGG/PIB e DLGG/PIB como séries próprias. A razão relaciona saldo de dívida ao fluxo anual do PIB; não confundir com a DPF do Tesouro, pois DBGG inclui estados e municípios e usa outro perímetro e metodologia.</p></div></div><div class="method-row"><span>03</span><div><strong>Variação do estoque</strong><p>A mudança do saldo entre meses pode refletir emissões líquidas, juros apropriados, câmbio, reconhecimento de passivos e outros ajustes. Não se interpreta toda alta do estoque como gasto primário novo.</p></div></div><div class="method-row"><span>04</span><div><strong>Juros</strong><p>Juros apropriados são contabilizados por competência e não significam pagamento em caixa do mesmo mês. A página dedicada descreve cálculo, exemplo e limitações da taxa implícita aproximada.</p><button class="subtle-link" @click="go('interest')">Abrir estudo de juros <ArrowUpRight class="ui-icon" :size="12" :stroke-width="2" /></button></div></div></article>
            <article class="panel data-jump"><div><span class="kicker">SÉRIE MENSAL COMPLETA</span><h3>Explore os 309 registros agregados</h3><p>Veja também componentes por tipo de título, indicadores macroeconômicos, fatores, emissões, resgates e carteiras.</p></div><button @click="activeData = 'monthly'; go('explorer')">Abrir explorador <b><ArrowUpRight class="ui-icon" :size="12" :stroke-width="2" /></b></button></article>
          </div>
        </section>
</template>
