<script setup>
import { inject, toRefs } from "vue";
import { ArrowUpRight } from "@lucide/vue";
import TrendChart from "../components/TrendChart.vue";
const { page, data, activeData, interestLatest, latestInterestYear, pretty, percent, month, interestChart, chartGuides, go } = toRefs(inject("dashboard"));
</script>

<template>
<section class="content inner-content">
          <div class="page-intro"><div><div class="eyebrow"><span></span> CUSTO FINANCEIRO DA DÍVIDA</div><h1 tabindex="-1">Juros apropriados.<br /><em>Métrica e método.</em></h1><p>Uma leitura separada de juros por competência, evolução anual e taxa implícita aproximada da DPF.</p></div><aside>ÚLTIMA COMPETÊNCIA<strong>{{ month(interestLatest?.data) }}</strong></aside></div>
          <div class="metrics three"><article class="metric metric-gold"><div class="metric-label">JUROS NO MÊS</div><strong>R$ {{ pretty(interestLatest?.juros_dpf_bilhoes, 1) }} <small>bi</small></strong><div class="metric-foot"><span>{{ month(interestLatest?.data) }}</span><i>R$ correntes</i></div></article><article class="metric metric-blue"><div class="metric-label">ÚLTIMO ANO COMPLETO · {{ latestInterestYear?.ano }}</div><strong>R$ {{ pretty(latestInterestYear?.juros_dpf_bilhoes, 1) }} <small>bi</small></strong><div class="metric-foot"><span>Apropriação anual</span><i>Tesouro Nacional</i></div></article><article class="metric metric-red"><div class="metric-label">RAZÃO JUROS / ESTOQUE MÉDIO</div><strong>{{ percent(latestInterestYear?.custo_implicito_aproximado_percentual) }}</strong><div class="metric-foot"><span>Indicador aproximado</span><i>Não é custo oficial</i></div></article></div>
          <div class="stacked-panels"><article class="panel"><div class="panel-heading"><div><span class="kicker">SÉRIE ANUAL · ANOS COMPLETOS</span><h3>Juros e razão aproximada</h3></div><span class="unit-pill">R$ bi · %</span></div><TrendChart :option="interestChart" :guide="chartGuides.interest" height="395px"/><div class="interest-legend"><span><i></i> Juros apropriados no ano</span><span><i></i> Taxa implícita aproximada</span></div><p class="panel-caption">Anos parciais ficam fora da comparação da taxa; a apropriação parcial ainda pode ser consultada na tabela mensal.</p></article>
            <article class="panel methods"><div class="panel-heading"><div><span class="kicker">DEFINIÇÃO OPERACIONAL</span><h3>O que entra no cálculo</h3></div></div><div class="method-row"><span>01</span><div><strong>Juros apropriados</strong><p>O Tesouro registra mensalmente juros e encargos apropriados por competência. É reconhecimento econômico no período, não necessariamente dinheiro pago naquele mês.</p></div></div><div class="method-row"><span>02</span><div><strong>Taxa implícita aproximada</strong><p><code>100 × soma dos juros apropriados no ano ÷ média dos estoques mensais da DPF</code>. Para {{ latestInterestYear?.ano }}, isso corresponde a R$ {{ pretty(latestInterestYear?.juros_dpf_bilhoes, 1) }} bi ÷ R$ {{ pretty(latestInterestYear?.estoque_medio_dpf_bilhoes, 1) }} bi = {{ percent(latestInterestYear?.custo_implicito_aproximado_percentual) }}.</p></div></div><div class="method-row"><span>03</span><div><strong>Limitações</strong><p>A razão é uma aproximação analítica: depende do estoque médio observado, da composição e indexadores da dívida e da contabilização por competência. Não equivale ao custo médio oficial nem ao serviço da dívida pago em caixa.</p></div></div></article>
            <article class="panel data-jump"><div><span class="kicker">DADOS PARA REPRODUZIR</span><h3>Juros mensais e anuais da DPF</h3><p>Inclui juros da dívida interna, externa e total, com estoque médio usado no indicador aproximado.</p></div><button @click="activeData = 'interestAnnual'; go('explorer')">Abrir a tabela <b><ArrowUpRight class="ui-icon" :size="12" :stroke-width="2" /></b></button></article></div>
        </section>
</template>
