<script setup>
import { inject, toRefs } from "vue";
import { ArrowUpRight } from "@lucide/vue";
import TrendChart from "../components/TrendChart.vue";
const { page, pibPeriod, data, activeData, pibQuarterly, pibLatest, pibSameQuarterLastYear, pibNominalGrowth, pretty, tri, percent, pibNominalChart, pibGrowthChart, pibSpendingChart, chartGuides, go } = toRefs(inject("dashboard"));
</script>

<template>
<section class="content inner-content">
          <div class="page-intro"><div><div class="eyebrow"><span></span> CONTAS NACIONAIS TRIMESTRAIS · IBGE</div><h1 tabindex="-1">O PIB brasileiro.<br /><em>Valor e crescimento real.</em></h1><p>Contas Nacionais Trimestrais do Brasil, com valores nominais, taxas oficiais de volume e composição da produção e da despesa. A série disponível cobre {{ data.pib.source.period_start }} a {{ data.pib.source.period_end }}.</p></div><aside>ÚLTIMO TRIMESTRE<strong>{{ pibLatest?.trimestre }}</strong><small>Coleta {{ data.pib.source.collected_at.slice(0, 10) }}</small></aside></div>
          <div class="metrics">
            <article class="metric metric-blue"><div class="metric-label">PIB NOMINAL · {{ pibLatest?.trimestre }}</div><strong>R$ {{ pretty(pibLatest?.pib_nominal_milhoes / 1e6, 2) }} <small>tri</small></strong><div class="metric-foot"><span>Valores correntes</span><i>{{ percent(pibNominalGrowth) }} nominal em 12 meses</i></div></article>
            <article class="metric metric-teal"><div class="metric-label">CRESCIMENTO REAL · ANO CONTRA ANO</div><strong>{{ percent(pibLatest?.pib_yoy_percentual) }}</strong><div class="metric-foot"><span>{{ pibLatest?.trimestre }} sobre mesmo tri anterior</span><i>IBGE · índice de volume</i></div></article>
            <article class="metric metric-gold"><div class="metric-label">CRESCIMENTO REAL · TRIMESTRE</div><strong>{{ percent(pibLatest?.pib_qoq_sa_percentual) }}</strong><div class="metric-foot"><span>Contra trimestre anterior</span><i>Ajuste sazonal · IBGE</i></div></article>
            <article class="metric metric-red"><div class="metric-label">ACUMULADO EM QUATRO TRIMESTRES</div><strong>{{ percent(pibLatest?.pib_four_quarters_percentual) }}</strong><div class="metric-foot"><span>Comparado aos quatro anteriores</span><i>Taxa publicada pelo IBGE</i></div></article>
          </div>
          <div class="pib-period-control panel" role="group" aria-label="Período de agregação do PIB">
            <span>PERÍODO DOS GRÁFICOS</span>
            <button :class="{ active: pibPeriod === 'quarterly' }" @click="pibPeriod = 'quarterly'">Trimestre</button>
            <button :class="{ active: pibPeriod === 'semestre' }" @click="pibPeriod = 'semestre'">Semestre</button>
            <button :class="{ active: pibPeriod === 'ano' }" @click="pibPeriod = 'ano'">Ano</button>
          </div>
          <div class="stacked-panels">
            <article class="panel"><div class="panel-heading"><div><span class="kicker">{{ pibPeriod === 'quarterly' ? 'VALORES TRIMESTRAIS' : pibPeriod === 'semestre' ? 'SOMA DOS TRIMESTRES DO SEMESTRE' : 'SOMA DOS TRIMESTRES DO ANO' }} · R$ CORRENTES</span><h3>PIB nominal e atividade econômica</h3></div><span class="unit-pill">R$ trilhões correntes</span></div><TrendChart :option="pibNominalChart" :guide="chartGuides.pibNominal" height="350px"/><p class="panel-caption">Valores correntes refletem volume produzido e preços do período. Agropecuária e serviços aparecem junto ao PIB para dar escala; não se somam ao PIB.</p></article>
            <article class="panel"><div class="panel-heading"><div><span class="kicker">ÍNDICE DE VOLUME · VARIAÇÃO REAL</span><h3>Crescimento por setor</h3></div><span class="unit-pill">{{ pibPeriod === 'semestre' ? 'Derivado · mesmo semestre anterior' : pibPeriod === 'ano' ? 'Acumulado no ano · IBGE' : 'Mesmo trimestre anterior · IBGE' }}</span></div><TrendChart :option="pibGrowthChart" :guide="chartGuides.pibGrowth" height="350px"/><p class="panel-caption">No modo trimestral, crescimento ano contra ano e trimestre contra trimestre ajustado sazonalmente são comparações diferentes. Semestre usa comparação derivada com o semestre equivalente anterior.</p></article>
            <article class="panel"><div class="panel-heading"><div><span class="kicker">COMPONENTES DA DESPESA · VOLUME</span><h3>Consumo, investimento e setor externo</h3></div><span class="unit-pill">Variação real (%)</span></div><TrendChart :option="pibSpendingChart" :guide="chartGuides.pibSpending" height="350px"/><p class="panel-caption">As séries seguem as taxas por componente publicadas pelo IBGE. Importações entram na identidade do PIB com sinal negativo; a taxa do componente não deve ser interpretada como contribuição direta ao crescimento total.</p></article>
            <article class="panel methods"><div class="panel-heading"><div><span class="kicker">MÉTRICAS, EXEMPLO E LIMITES</span><h3>Como ler as séries do PIB</h3></div></div>
              <div class="method-row"><span>01</span><div><strong>Nominal e real</strong><p>O valor nominal é o PIB em milhões de reais correntes. Sua variação combina mudança de quantidade e de preços. Para medir crescimento da produção, usamos índices de volume e taxas reais oficiais, que retiram a variação de preços.</p></div></div>
              <div class="method-row"><span>02</span><div><strong>Trimestre a trimestre com ajuste sazonal</strong><p>Compara o trimestre com o imediatamente anterior após ajuste sazonal do IBGE. Ajuda a observar a direção recente sem confundir padrões recorrentes do calendário com mudança de atividade.</p></div></div>
              <div class="method-row"><span>03</span><div><strong>Semestre e ano</strong><p>Os valores nominais são somados entre trimestres. Exemplo: o PIB de {{ pibLatest?.trimestre }} é R$ {{ pretty(pibLatest?.pib_nominal_milhoes / 1e6, 2) }} trilhões; a comparação nominal usa {{ pibSameQuarterLastYear?.trimestre }} (R$ {{ pretty(pibSameQuarterLastYear?.pib_nominal_milhoes / 1e6, 2) }} tri), resultando em {{ percent(pibNominalGrowth) }}. Para o semestre, a taxa real derivada compara a média dos índices encadeados dos dois trimestres com a média do semestre equivalente anterior; exige os dois trimestres em ambos os períodos e não é uma taxa semestral publicada pelo IBGE. O índice encadeado não representa nível monetário aditivo.</p></div></div>
              <div class="method-row"><span>04</span><div><strong>Acumulado no ano e em quatro trimestres</strong><p>São taxas publicadas pelo IBGE, não intercambiáveis com a variação trimestral. No gráfico anual, a taxa acumulada no ano vem do último trimestre disponível de cada ano; anos incompletos são mantidos como parciais.</p></div></div>
              <div class="method-row"><span>05</span><div><strong>Setores e componentes da despesa</strong><p>Agropecuária, indústria e serviços detalham a produção. Consumo das famílias e do governo, formação de capital, estoques, exportações e importações detalham a despesa. São perspectivas contábeis do mesmo PIB e não devem ser somadas umas às outras.</p></div></div>
              <div class="method-row"><span>06</span><div><strong>Revisões e preservação</strong><p>O IBGE revê a série quando incorpora fontes e resultados anuais do Sistema de Contas Nacionais. As respostas consultadas e a data da coleta ficam preservadas em <code>data/raw/ibge/</code>; esta visualização usa a versão mais recente coletada em {{ data.pib.source.collected_at.slice(0, 10) }}.</p></div></div>
            </article>
            <article class="panel data-jump"><div><span class="kicker">SÉRIE COMPLETA · 1996–2026</span><h3>Dados e fontes para reprodução</h3><p>122 trimestres, tabelas oficiais do SIDRA 1846, 1620 e 5932; arquivo bruto preservado e tabelas processadas disponíveis para download no explorador.</p></div><button @click="activeData = 'pibQuarterly'; go('explorer')">Explorar PIB <b><ArrowUpRight class="ui-icon" :size="12" :stroke-width="2" /></b></button></article>
          </div>
        </section>
</template>
