<script setup>
import { inject, toRefs } from "vue";
import { ExternalLink, ArrowUpRight } from "@lucide/vue";
import TrendChart from "../components/TrendChart.vue";
const { page, data, activeData, purchasingPowerLatest, pretty, percent, purchasingPowerChart, chartGuides, go } = toRefs(inject("dashboard"));
</script>

<template>
<section class="content inner-content">
          <div class="page-intro"><div><div class="eyebrow"><span></span> IPCA · PODER DE COMPRA DO REAL</div><h1 tabindex="-1">O real desde 1994.<br /><em>O que a inflação mudou.</em></h1><p>Quanto os preços subiram desde a entrada em circulação do real e quanto do poder de compra original permanece, com base no IPCA oficial até {{ purchasingPowerLatest?.data }}.</p></div><aside>BASE DE COMPARAÇÃO<strong>Julho de 1994</strong><small>Atualizado até {{ purchasingPowerLatest?.data }}</small></aside></div>
          <div class="metrics">
            <article class="metric metric-blue"><div class="metric-label">INFLAÇÃO ACUMULADA DESDE 1994</div><strong>{{ percent(purchasingPowerLatest?.inflacao_acumulada_desde_jul_1994_percentual) }}</strong><div class="metric-foot"><span>IPCA composto</span><i>Jul/1994–{{ purchasingPowerLatest?.data }}</i></div></article>
            <article class="metric metric-red"><div class="metric-label">PODER DE COMPRA PERDIDO</div><strong>{{ percent(purchasingPowerLatest?.perda_poder_compra_percentual) }}</strong><div class="metric-foot"><span>De R$ 1 em jul/1994</span><i>Medida doméstica</i></div></article>
            <article class="metric metric-teal"><div class="metric-label">R$ 100 DE JULHO/1994</div><strong>R$ {{ pretty(purchasingPowerLatest?.preco_cesta_r_100_jul_1994, 2) }}</strong><div class="metric-foot"><span>Cesta-base equivalente</span><i>Valores correntes de {{ purchasingPowerLatest?.data }}</i></div></article>
            <article class="metric metric-gold"><div class="metric-label">IPCA DO ÚLTIMO MÊS</div><strong>{{ percent(purchasingPowerLatest?.ipca_mensal_percentual) }}</strong><div class="metric-foot"><span>{{ purchasingPowerLatest?.data }}</span><i>IBGE · Brasil</i></div></article>
          </div>
          <div class="stacked-panels">
            <article class="panel"><div class="panel-heading"><div><span class="kicker">PREÇOS ACUMULADOS · JULHO/1994 = 100</span><h3>Quanto custa hoje uma cesta de R$ 100 de 1994</h3></div><span class="unit-pill">R$ correntes</span></div><TrendChart :option="purchasingPowerChart" :guide="chartGuides.purchasingPower" height="390px"/><p class="panel-caption">O índice é construído pelas variações mensais do IPCA, com julho de 1994 como base e composição a partir de agosto. É uma referência média nacional de preços, não uma cesta fixa observada em lojas nem o custo de vida pessoal de cada família.</p></article>
            <article class="panel methods"><div class="panel-heading"><div><span class="kicker">CÁLCULO, EXEMPLO E LIMITES</span><h3>Inflação não é o mesmo que perda de poder de compra</h3></div></div>
              <div class="method-row"><span>01</span><div><strong>Inflação acumulada</strong><p>As variações mensais são compostas: o fator total é o produto de (1 + IPCA do mês). Desde agosto de 1994, o fator acumulado é {{ pretty(purchasingPowerLatest?.indice_precos_jul_1994_100 / 100, 4) }}; isso corresponde a {{ percent(purchasingPowerLatest?.inflacao_acumulada_desde_jul_1994_percentual) }} de aumento no nível de preços medido pelo IPCA.</p></div></div>
              <div class="method-row"><span>02</span><div><strong>Perda do poder de compra</strong><p>A perda é calculada pelo inverso do aumento dos preços: 1 − (1 ÷ {{ pretty(purchasingPowerLatest?.indice_precos_jul_1994_100 / 100, 4) }}). Assim, R$ 1 mantém cerca de {{ percent(purchasingPowerLatest?.poder_compra_remanescente_percentual) }} do poder de compra que tinha na base; a perda é {{ percent(purchasingPowerLatest?.perda_poder_compra_percentual) }}. Esse percentual não é igual à inflação acumulada.</p></div></div>
              <div class="method-row"><span>03</span><div><strong>Exemplo em reais</strong><p>Uma cesta que custava R$ 100 em julho de 1994 custaria aproximadamente R$ {{ pretty(purchasingPowerLatest?.preco_cesta_r_100_jul_1994, 2) }} em {{ purchasingPowerLatest?.data }}, se seu preço tivesse acompanhado exatamente o IPCA médio. Esse exemplo serve para converter valores nominais de épocas diferentes, não para dizer quanto qualquer produto específico custa hoje.</p></div></div>
              <div class="method-row"><span>04</span><div><strong>Data-base e moeda</strong><p>O real entrou em circulação em 1º de julho de 1994. Julho é a base do índice; por isso, o acumulado começa com a variação de agosto, evitando incluir a inflação de junho para julho como se toda ela tivesse ocorrido sob o real. Esta análise trata do poder de compra interno, não da taxa de câmbio do real frente ao dólar ou outras moedas.</p></div></div>
              <div class="method-row"><span>05</span><div><strong>IPCA e experiência de cada família</strong><p>O IPCA representa uma cesta e uma população de referência nacionais. A inflação sentida por cada pessoa pode ser maior ou menor conforme renda, região e composição do consumo. O índice também pode ser revisto quando o IBGE corrige dados.</p><a href="https://www.ibge.gov.br/estatisticas/economicas/precos-e-custos/9256-indice-nacional-de-precos-ao-consumidor-amplo.html" target="_blank" rel="noreferrer">Metodologia e séries históricas do IPCA no IBGE <ExternalLink class="ui-icon" :size="12" /></a></div></div>
              <div class="method-row"><span>06</span><div><strong>O que estudar</strong><p>Índices de preços, inflação composta, números-índice, cesta de consumo, correção monetária, inflação pessoal e diferença entre preços, salários e taxa de câmbio.</p></div></div>
            </article>
            <article class="panel data-jump"><div><span class="kicker">SÉRIE MENSAL · {{ data.purchasing_power.source.period_start }}–{{ data.purchasing_power.source.period_end }}</span><h3>IPCA mensal usado no cálculo</h3><p>Variações mensais oficiais preservadas desde a base do real e série acumulada calculada pelo painel. Coleta em {{ data.purchasing_power.source.collected_at }}.</p></div><button @click="activeData = 'purchasingPowerMonthly'; go('explorer')">Explorar série <ArrowUpRight class="ui-icon" :size="12" /></button></article>
          </div>
        </section>
</template>
