<script setup>
import { inject, toRefs } from "vue";
import { ArrowUpRight } from "@lucide/vue";
import TrendChart from "../components/TrendChart.vue";
const { page, chartStart, data, activeData, socialLatest, bpcPrevious, bpcGrowth, bpcRepassePerBeneficiary, pretty, percent, socialCoverageChart, socialSpendChart, chartGuides, go } = toRefs(inject("dashboard"));
</script>

<template>
<section class="content inner-content">
          <div class="page-intro"><div><div class="eyebrow"><span></span> TRANSFERÊNCIA DE RENDA E PROTEÇÃO SOCIAL</div><h1 tabindex="-1">Programas sociais.<br /><em>Escala e cobertura.</em></h1><p>Série histórica do BPC e um retrato comparável dos principais repasses federais em 2024, com unidades e limites claramente identificados.</p></div><aside>ÚLTIMO ANO HISTÓRICO<strong>{{ socialLatest?.ano }}</strong></aside></div>
          <div class="metrics"><article class="metric metric-blue"><div class="metric-label">BPC · BENEFICIÁRIOS</div><strong>{{ pretty(socialLatest?.beneficiarios_total, 0) }}</strong><div class="metric-foot"><span>PCD e idosos</span><i>{{ socialLatest?.ano }} · MDS</i></div></article><article class="metric metric-teal"><div class="metric-label">BPC · REPASSES</div><strong>R$ {{ pretty(socialLatest?.repasse_total_brl / 1e9, 2) }} <small>bi</small></strong><div class="metric-foot"><span>Valores correntes</span><i>{{ socialLatest?.ano }} · VIS Data</i></div></article><article class="metric metric-gold"><div class="metric-label">BPC · CRESCIMENTO ANUAL</div><strong>{{ percent(bpcGrowth) }}</strong><div class="metric-foot"><span>Beneficiários</span><i>{{ socialLatest?.ano }} sobre {{ bpcPrevious?.ano }}</i></div></article><article class="metric metric-red"><div class="metric-label">AUXÍLIO GÁS · COBERTURA</div><strong>{{ pretty(data.social.auxilio_gas_2024.cobertura_media_ciclo / 1e6, 1) }} <small>mi</small></strong><div class="metric-foot"><span>Famílias por ciclo</span><i>Bimestral · 2024</i></div></article></div>
          <div class="stacked-panels"><article class="panel"><div class="panel-heading"><div><span class="kicker">BPC · {{ chartStart === '2012' ? '2012' : '2004' }}–{{ socialLatest?.ano }}</span><h3>Beneficiários por grupo</h3></div><span class="unit-pill">Milhões de pessoas</span></div><TrendChart :option="socialCoverageChart" :guide="chartGuides.bpc" height="340px"/><p class="panel-caption">O painel anual do MDS reporta grupos e total de beneficiários; a tabela histórica também registra repasses correntes.</p></article><article class="panel"><div class="panel-heading"><div><span class="kicker">TRANSFERÊNCIAS REPORTADAS · 2024</span><h3>Bolsa Família e BPC</h3></div><span class="unit-pill">R$ bilhões correntes</span></div><TrendChart :option="socialSpendChart" :guide="chartGuides.socialSpend" height="270px"/><p class="panel-caption">Bolsa Família: R$ 168,3 bi e mais de 20,86 milhões de famílias contempladas ao longo do ano. BPC: R$ 102,27 bi na série anual VIS Data. Fontes e perímetros contábeis podem diferir.</p></article>
            <article class="panel methods"><div class="panel-heading"><div><span class="kicker">MÉTRICAS, EXEMPLO E LIMITES</span><h3>Como interpretar</h3></div></div><div class="method-row"><span>01</span><div><strong>BPC — cobertura e repasse</strong><p>Em {{ socialLatest?.ano }}, a base registra {{ pretty(socialLatest?.beneficiarios_total, 0) }} beneficiários e R$ {{ pretty(socialLatest?.repasse_total_brl / 1e9, 2) }} bilhões em repasses. A divisão dá aproximadamente R$ {{ pretty(bpcRepassePerBeneficiary, 0) }} por pessoa contada na referência anual; é apenas razão descritiva, não valor mensal individual.</p></div></div><div class="method-row"><span>02</span><div><strong>Bolsa Família — famílias</strong><p>O MDS informou mais de 20,86 milhões de famílias contempladas ao longo de 2024 e R$ 168,3 bilhões transferidos. A cobertura anual não deve ser interpretada como número simultâneo de famílias em um mês.</p></div></div><div class="method-row"><span>03</span><div><strong>Auxílio Gás — pagamento bimestral</strong><p>O MDS informa cobertura média de 5,7 milhões de famílias por ciclo entre fevereiro e dezembro de 2024. Ciclos não equivalem a famílias únicas no ano. Não somamos grupos de programas: além de unidades distintas, públicos podem se sobrepor.</p></div></div><div class="method-row"><span>04</span><div><strong>Valores nominais</strong><p>Repasses do BPC crescem com cobertura, reajuste do salário mínimo e preços. A série não está deflacionada e não mede impacto causal, redução da pobreza ou poder de compra.</p></div></div></article>
            <article class="panel data-jump"><div><span class="kicker">TABELAS FONTE</span><h3>Série anual e comparação de programas</h3><p>Dados agregados preservados no bundle do painel; não usamos CPF, NIS ou pagamentos individualizados.</p></div><button @click="activeData = 'bpcAnnual'; go('explorer')">Explorar as tabelas <b><ArrowUpRight class="ui-icon" :size="12" :stroke-width="2" /></b></button></article></div>
        </section>
</template>
