<script setup>
import { inject, toRefs } from "vue";
import { ArrowUpRight } from "@lucide/vue";
import TrendChart from "../components/TrendChart.vue";
const { page, data, activeData, taxLatest, taxAnnualRunning, taxYoy, taxGeneralLatest, pretty, tri, percent, month, taxMonthlyChart, taxBurdenChart, chartGuides, go } = toRefs(inject("dashboard"));
</script>

<template>
<section class="content inner-content">
          <div class="page-intro"><div><div class="eyebrow"><span></span> ARRECADAÇÃO DAS RECEITAS FEDERAIS · RECEITA FEDERAL</div><h1 tabindex="-1">Impostos arrecadados.<br /><em>Um contador oficial.</em></h1><p>Arrecadação federal mensal em valores correntes, desde {{ data.taxes.source.period_start }}. O contador soma apenas os meses publicados no ano e é atualizado quando a Receita divulga novos resultados.</p></div><aside>ÚLTIMO MÊS PUBLICADO<strong>{{ month(taxLatest?.data) }}</strong><small>Coleta {{ data.taxes.source.collected_at }}</small></aside></div>
          <div class="metrics">
            <article class="metric metric-blue"><div class="metric-label">ACUMULADO FEDERAL · {{ taxLatest?.ano }}</div><strong>R$ {{ pretty(taxAnnualRunning / 1e6, 3) }} <small>tri</small></strong><div class="metric-foot"><span>Jan–{{ String(taxLatest?.mes).padStart(2, '0') }}/{{ taxLatest?.ano }}</span><i>Total geral · valores correntes</i></div></article>
            <article class="metric metric-teal"><div class="metric-label">ARRECADAÇÃO NO MÊS</div><strong>R$ {{ pretty(taxLatest?.arrecadacao_total_federal_milhoes / 1000, 2) }} <small>bi</small></strong><div class="metric-foot"><span>{{ month(taxLatest?.data) }}</span><i>RFB + outros órgãos</i></div></article>
            <article class="metric metric-gold"><div class="metric-label">VARIAÇÃO NOMINAL · 12 MESES</div><strong>{{ percent(taxYoy) }}</strong><div class="metric-foot"><span>Mesmo mês do ano anterior</span><i>Sem descontar inflação</i></div></article>
            <article class="metric metric-red"><div class="metric-label">CARGA TRIBUTÁRIA · GOVERNO GERAL</div><strong>{{ percent(taxGeneralLatest?.governo_geral_percentual_pib) }}</strong><div class="metric-foot"><span>União, estados e municípios</span><i>{{ taxGeneralLatest?.ano }} · Tesouro Nacional</i></div></article>
          </div>
          <div class="stacked-panels">
            <article class="panel"><div class="panel-heading"><div><span class="kicker">{{ data.taxes.source.period_start }} — {{ data.taxes.source.period_end }} · VALORES NOMINAIS</span><h3>Arrecadação federal por mês</h3></div><span class="unit-pill">R$ bilhões correntes</span></div><TrendChart :option="taxMonthlyChart" :guide="chartGuides.taxes" height="360px"/><p class="panel-caption">A linha “Total federal” inclui receitas administradas pela Receita Federal e por outros órgãos. A parcela administrada pela RFB está disponível no detalhamento mais recente (2021 em diante). Valores não corrigidos pela inflação.</p></article>
            <article class="panel"><div class="panel-heading"><div><span class="kicker">CARGA TRIBUTÁRIA BRUTA · 2010–{{ taxGeneralLatest?.ano }}</span><h3>Tributos arrecadados em relação ao PIB</h3></div><span class="unit-pill">Percentual do PIB</span></div><TrendChart :option="taxBurdenChart" :guide="chartGuides.taxBurden" height="340px"/><p class="panel-caption">Indicador anual do Governo Geral, que soma as esferas federal, estadual e municipal. É uma medida de carga tributária do sistema público inteiro, não um complemento mensal da arrecadação federal.</p></article>
            <article class="panel methods"><div class="panel-heading"><div><span class="kicker">MÉTRICA, EXEMPLO E LIMITES</span><h3>Como funciona o contador</h3></div></div>
              <div class="method-row"><span>01</span><div><strong>Acumulado observado</strong><p>O contador exibe R$ {{ pretty(taxAnnualRunning / 1e6, 3) }} trilhões de arrecadação federal entre janeiro e {{ month(taxLatest?.data) }} de {{ taxLatest?.ano }}. É a soma dos valores mensais já divulgados, sem projeção diária e sem estimar dias ainda não publicados.</p></div></div>
              <div class="method-row"><span>02</span><div><strong>O que entra no total federal</strong><p>A série histórica da Receita Federal define o total como receitas administradas pela RFB mais receitas administradas por outros órgãos. A planilha histórica cobre 1994–2025; para 2021 em diante usamos os dados mensais do anexo mais recente, que também detalha as duas parcelas.</p></div></div>
              <div class="method-row"><span>03</span><div><strong>Valores nominais e inflação</strong><p>Os valores são nominais. A variação de {{ percent(taxYoy) }} em 12 meses compara {{ month(taxLatest?.data) }} com o mesmo mês do ano anterior e mistura mudanças de preços, atividade econômica, alíquotas e regras. Não representa crescimento real da carga.</p></div></div>
              <div class="method-row"><span>04</span><div><strong>Carga tributária bruta</strong><p>O Tesouro Nacional calcula a carga tributária do Governo Geral por esfera e como proporção do PIB. É uma série anual consolidada — em {{ taxGeneralLatest?.ano }}, {{ percent(taxGeneralLatest?.governo_geral_percentual_pib) }} do PIB — com escopo diferente da arrecadação mensal federal.</p></div></div>
              <div class="method-row"><span>05</span><div><strong>Revisões e atualização</strong><p>A Receita pode revisar os dados históricos e publica relatórios mensais. O material bruto consultado fica em <code>data/raw/tributos/</code> e a data de coleta é registrada acima. Para atualizar no futuro, substitua os arquivos oficiais e rode <code>uv run python scripts/processar_impostos.py</code> e <code>uv run python web/scripts/build_data.py</code>.</p></div></div>
            </article>
            <article class="panel data-jump"><div><span class="kicker">SÉRIES COMPLETAS · 1994–2026</span><h3>Dados para explorar e baixar</h3><p>Arrecadação federal mensal e anual, detalhamento por esfera e carga tributária bruta do Governo Geral.</p></div><button @click="activeData = 'taxesMonthly'; go('explorer')">Explorar dados <b><ArrowUpRight class="ui-icon" :size="12" :stroke-width="2" /></b></button></article>
          </div>
        </section>
</template>
